USE sakila;
show tables;


-- List the number of films per category.
SELECT * FROM sakila.film_category;
SELECT * FROM sakila.film;

SELECT fc.category_id, COUNT(f.film_id) AS Total_film FROM sakila.film AS f
JOIN sakila.film_category AS fc
WHERE f.film_id = fc.film_id
GROUP BY fc.category_id;

-- Retrieve the store ID, city, and country for each store.
WITH cte_store AS(
SELECT s.store_id, city_id FROM sakila.address AS a		
JOIN sakila.store AS s
ON a.address_id = s.address_id
)
SELECT ci.city, co.country, store_id FROM cte_store
JOIN sakila.city AS ci
ON cte_store.city_id = ci.city_id
JOIN sakila.country AS co
ON ci.country_id = co.country_id;

-- #Solution
-- SELECT s.store_id, c.city, co.country
-- FROM store s
-- JOIN address a ON s.address_id = a.address_id
-- JOIN city c ON a.city_id = c.city_id
-- JOIN country co ON c.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT * FROM sakila.payment;
SELECT * FROM sakila.rental;
SELECT * FROM sakila.store;

SELECT s.store_id,ci.city,co.country, SUM(amount) AS total_revenue FROM sakila.payment AS p
JOIN sakila.store AS s
ON p.staff_id = s.manager_staff_id
JOIN sakila.address AS a
ON a.address_id = s.address_id
JOIN sakila.city AS ci
ON a.city_id = ci.city_id
JOIN sakila.country AS co
ON ci.country_id = co.country_id
GROUP BY s.store_id;


-- Determine the average running time of films for each category.
SELECT fc.category_id, ROUND(SUM(f.length)/COUNT(f.film_id),2) AS avg_length, COUNT(f.film_id) AS Total_film FROM sakila.film AS f
JOIN sakila.film_category AS fc
WHERE f.film_id = fc.film_id
GROUP BY fc.category_id;

-- Bonus:

-- Identify the film categories with the longest average running time.
CREATE TEMPORARY TABLE IF NOT EXISTS sakila.category_avg_film_length
SELECT fc.category_id, ROUND(SUM(f.length)/COUNT(f.film_id),2) AS avg_length FROM sakila.film AS f
JOIN sakila.film_category AS fc
WHERE f.film_id = fc.film_id
GROUP BY fc.category_id;

SELECT MAX(avg_length) FROM sakila.category_avg_film_length;

-- Display the top 10 most frequently rented movies in descending order.
SELECT * FROM sakila.rental;
SELECT * FROM sakila.inventory;
SELECT * FROM sakila.film;

CREATE TEMPORARY TABLE IF NOT EXISTS sakila.film_available_inv
SELECT i.inventory_id, title FROM sakila.film AS f
JOIN sakila.inventory AS i
ON f.film_id = i.film_id;

SELECT * FROM sakila.film_available_inv;

SELECT r.inventory_id, COUNT(r.inventory_id), title  FROM sakila.film_available_inv AS fai
JOIN sakila.rental AS r
ON fai.inventory_id = r.inventory_id
GROUP BY r.inventory_id;

-- Determine if "Academy Dinosaur" can be rented from Store 1.


-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

-- ================================================================
-- Here are some tips to help you successfully complete the lab:

-- Tip 1: This lab involves joins with multiple tables, which can be challenging. Take your time and follow the steps we discussed in class:

-- Make sure you understand the relationships between the tables in the database. This will help you determine which tables to join and which columns to use in your joins.
-- Identify a common column for both tables to use in the ON section of the join. If there isn't a common column, you may need to add another table with a common column.
-- Decide which table you want to use as the left table (immediately after FROM) and which will be the right table (immediately after JOIN).
-- Determine which table you want to include all records from. This will help you decide which type of JOIN to use. If you want all records from the first table, use a LEFT JOIN. If you want all records from the second table, use a RIGHT JOIN. If you want records from both tables only where there is a match, use an INNER JOIN.
-- Use table aliases to make your queries easier to read and understand. This is especially important when working with multiple tables.
-- Write the query

-- Tip 2: Break down the problem into smaller, more manageable parts. For example, you might start by writing a query to retrieve data from just two tables before adding additional tables to the join. 
-- Test your queries as you go, and check the output carefully to make sure it matches what you expect.
-- This process takes time, so be patient and go step by step to build your query incrementally.